groups:
  - name: linux-alerts
    rules:
      - alert: HighCPUUsage
        expr: avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance) < 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage: {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.8
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Memory Usage: {{ $labels.instance }}"
          
  - name: windows_alerts
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[15s])) * 100) > 80
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 1 minute on {{ $labels.instance }}."

      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: 1 - (windows_memory_available_bytes / windows_memory_physical_total_bytes) > 0.8
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "High Memory Usage on {{ $labels.instance }}"
          description: "Memory usage is above 90% for more than 1 minute on {{ $labels.instance }}."
